# The hashes for all user account passwords should be stored in the file
# "/etc/shadow" and never in "/etc/passwd", which is readable by all users.
#
# This module will disable any account that uses a hash in the /etc/passwd file
#
- replace: dest="/etc/passwd" regexp='(^[a-zA-Z0-9]+:)([a-zA-Z0-9]{2,99})(:.*$)' replace="\1*\3" backup=yes


