# The rexecd service uses unencrypted network communications, which means that data 
# from the login session, including passwords and all other information transmitted
# during the session, can be stolen by eavesdroppers on the network.

- stat: path=/etc/init.d/telnetd
  register: telnetd

- service: enabled=no state=stopped name=telnetd
  when: not logonly and telnetd.stat.exists

# Ubuntu tends to use the /etc/inetd.conf file instead of a service.  The previous lines are kept for service compatibility
- lineinfile: dest=/etc/inetd.conf state=absent regexp='.*in\.telnetd$' backup=yes
  when: not logonly