# Configuring this setting for the SSH daemon provides additional assurance
# that remote login via SSH will require a password, even in the event
# of misconfiguration elsewhere.

- replace: dest=/etc/ssh/sshd_config regexp='^[#].*(PermitEmptyPasswords).*' replace='\1 no'