# Accepting source-routed packets in the IPv4 protocol has few legitimate uses.
# It should be disabled unless it is absolutely required.

- replace: dest=/etc/sysctl.conf regexp='^[#].*(net.ipv4.conf.all.accept_source_route).*' replace='\1=0'