# Accepting "secure" ICMP redirects (from those gateways listed as
# default gateways) has few legitimate uses. It should be disabled
# unless it is absolutely required.

- replace: dest=/etc/sysctl.conf regexp='^[#].*(net.ipv4.conf.all.secure_redirects).*' replace='\1=0'