# The "/etc/group" file contains information regarding groups that are
# configured on the system. Protection of this file is important for system security.

- file: path=/etc/group group=root
  when: not logonly