# A locally logged-in user who presses Ctrl-Alt-Delete, when at the console, can reboot the system.
# If accidentally pressed, as could happen in the case of mixed OS environment, this can create the
# risk of short-term loss of availability of systems due to unintentional reboot.
# In the GNOME graphical environment, risk of unintentional reboot from the Ctrl-Alt-Delete sequence
# is reduced because the user will be prompted before any action is taken.

- replace: dest="/etc/init/control-alt-delete.conf" regexp='(^exec[\s]+).*(shutdown|poweroff).*' replace='\1 echo "The system cannot be stopped using CTL-ALT-DELETE"' backup=yes
  when: not logonly
